### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by migueruiz** [pluque01/CofreSagradoVirtual#7]
Hola @pluque01, me ha tocado trabajar sobre tu repositorio, hay que elegir un lenguaje para tu proyecto, ¿Con cuál te gustaría realizarlo?

**Comment by pluque01** [comment]
Hola @migueruiz
La verdad es que me hace ilusión hacerlo con Go. ¿Qué te parece? :))

**Comment by migueruiz** [comment]
Me parece correcto, gracias!!
