### ISSUE TITLE
Propuesta y organización de estructura de datos

### ISSUE THREAD

**Issue by migueruiz** [pluque01/CofreSagradoVirtual#9]
Hola, @pluque01  👋. Leyendo las HU y, en concreto [[HU01] María Rodriguez](#2), he reflexionado sobre qué se debe incluir, por ahora, en el proyecto. Las entidades que he identificado las he organizado como sigue:

## Clientes
En esta clase se representan los datos que identifican y caracterizan los clientes que tiene la empresa: 
- nombre
- apellidos
- numero de teléfono

Dime cómo lo ves, qué cambiarías y/o eliminarías, etc. Espero tu respuesta 😁.

**Comment by pluque01** [comment]
Te pido perdón pero me acabo de dar cuenta que no había actualizado las historias de usuario de las issues con las de la rama main. 

Quitando eso no creo que sea necesario almacenar información acerca del propietario del negocio, ya que no forma parte de la lógica de negocio.

**Comment by migueruiz** [comment]
De acuerdo! Lo he cambiado según me has comentado, si crees que se necesita algún otro cambio, estaré encantado de arreglarlo! Si no, sigo con el trabajo. 😄

**Comment by pluque01** [comment]
Lo veo bien :)) 👍
